from pyservicenow.types.exceptions._py_snow_exception import PysnowException

class InvalidUsage(PysnowException):
    pass